#  mysql:
#   dns:root:aNXvf&qYQ4NJTt7DPzPdGoGg@tcp(127.0.0.1:3306)/ginchat?parseTime=true

# app.yml

mysql:
  username: root
  password: aNXvf&qYQ4NJTt7DPzPdGoGg
  host: 127.0.0.1
  port: 3306
  dbname: ginchat

redis:
  Addr: "18.166.166.171:6379"
  Password: "hhb123456"
  DB: 5
  poolSize: 30
  minIdleConn: 30

